// HumanoidVerse — Robot Database
const ROBOTS = [
  {
    id: "atlas",
    name: "Atlas",
    manufacturer: "Boston Dynamics",
    country: "🇺🇸 USA",
    year: 2024,
    generation: "Electric",
    status: "Enterprise Pilot",
    category: "Industrial",
    tagline: "The Most Agile Humanoid Ever Built",
    description: "Boston Dynamics' fully electric Atlas represents the pinnacle of dynamic humanoid robotics. Designed for real-world industrial applications, it features unprecedented agility, heavy payload capacity, and IP67 durability rating.",
    specs: {
      height: 190, weight: 90, dof: 56,
      speed: 2.5, payload: 50, battery: 4,
      ip_rating: "IP67", actuator: "Electric",
      connectivity: "Wi-Fi 6, 5G"
    },
    pros: ["Unmatched agility & acrobatics", "56 DoF — most articulated humanoid", "50kg peak payload capacity", "IP67 industrial durability"],
    cons: ["Extremely high cost", "Limited commercial availability", "4-hour battery life", "Closed ecosystem"],
    price: "Contact for Quote (~$150K+)",
    image: "atlas.webp",
    color: "#00b4d8",
    video: "https://www.youtube.com/watch?v=29ECwExc-_M"
  },
  {
    id: "optimus",
    name: "Optimus Gen 3",
    manufacturer: "Tesla",
    country: "🇺🇸 USA",
    year: 2025,
    generation: "Gen 3",
    status: "R&D / Internal Testing",
    category: "General Purpose",
    tagline: "A Robot for Everyone",
    description: "Tesla's Optimus aims to be the world's most affordable general-purpose humanoid robot. Leveraging Tesla's AI expertise, manufacturing scale, and supply chain, Optimus targets mass production at consumer-accessible prices.",
    specs: {
      height: 173, weight: 57, dof: 50,
      speed: 2.2, payload: 20, battery: 8,
      ip_rating: "IP54", actuator: "Electric",
      connectivity: "Wi-Fi 6, Tesla Network"
    },
    pros: ["Lowest target price ($20-30K)", "Tesla AI & FSD technology", "8-hour battery life", "50 actuators — 22 DoF hands"],
    cons: ["Still in R&D phase", "Limited real-world demos", "No commercial deployments yet", "Ambitious timeline"],
    price: "$20,000-$30,000 (Target)",
    image: "optimus.webp",
    color: "#e63946",
    video: "https://www.youtube.com/watch?v=cpraXaw7dyc"
  },
  {
    id: "figure-03",
    name: "Figure 03",
    manufacturer: "Figure AI",
    country: "🇺🇸 USA",
    year: 2025,
    generation: "3rd Gen",
    status: "Commercial Pilot",
    category: "AI-Native",
    tagline: "The World's Most Intelligent Humanoid",
    description: "Figure 03 represents the cutting edge of AI-native humanoid robotics. With deep LLM integration, natural language understanding, and autonomous task learning, it's designed to work alongside humans in manufacturing environments.",
    specs: {
      height: 170, weight: 61, dof: 44,
      speed: 1.2, payload: 20, battery: 5,
      ip_rating: "IP54", actuator: "Electric",
      connectivity: "Wi-Fi 6, 5G, Helix AI Cloud"
    },
    pros: ["Best-in-class AI (Helix VLA)", "Tactile fingertips (3g sensitivity)", "BMW commercial partnership", "Wireless inductive charging"],
    cons: ["High cost", "Cloud-dependent AI", "Early commercial stage", "Limited outdoor capability"],
    price: "Contact for Quote (~$60K-100K)",
    image: "figure03.webp",
    color: "#f77f00",
    video: "https://www.youtube.com/watch?v=Q5MKo3SnplI"
  },
  {
    id: "digit",
    name: "Digit",
    manufacturer: "Agility Robotics",
    country: "🇺🇸 USA",
    year: 2024,
    generation: "Production",
    status: "Commercial Deployment",
    category: "Logistics",
    tagline: "The First Commercially Deployed Humanoid",
    description: "Digit is the most mature commercial humanoid robot, specifically designed for warehouse logistics. It's the first humanoid generating real revenue in real-world deployments, handling tote manipulation at facilities like Amazon.",
    specs: {
      height: 175, weight: 64, dof: 28,
      speed: 1.5, payload: 16, battery: 4,
      ip_rating: "IP54", actuator: "Electric",
      connectivity: "Wi-Fi 6, Agility Arc Fleet"
    },
    pros: ["Most commercially mature", "Revenue-generating deployments", "Amazon partnership", "Purpose-built for logistics"],
    cons: ["Limited to logistics use case", "Lower dexterity than competitors", "Utilitarian design", "High per-unit cost"],
    price: "~$250K (Lease options available)",
    image: "digit.webp",
    color: "#2ec4b6",
    video: "https://www.youtube.com/watch?v=4OmwsBa6K8o"
  },
  {
    id: "unitree-g1",
    name: "G1",
    manufacturer: "Unitree Robotics",
    country: "🇨🇳 China",
    year: 2024,
    generation: "1st Gen",
    status: "Available for Purchase",
    category: "Research & Education",
    tagline: "The Most Affordable Humanoid Robot",
    description: "Unitree G1 disrupted the market with its incredibly low price point, making humanoid robotics accessible to researchers, educators, and hobbyists worldwide. Despite its price, it offers impressive capabilities.",
    specs: {
      height: 132, weight: 35, dof: 23,
      speed: 2.0, payload: 3, battery: 2,
      ip_rating: "IP54", actuator: "Electric",
      connectivity: "Wi-Fi 6, Bluetooth 5.2"
    },
    pros: ["Lowest price on market ($16K)", "Open-source friendly", "Compact & lightweight", "Large developer community"],
    cons: ["Small form factor", "Low payload capacity", "Short battery life", "Build quality concerns"],
    price: "$16,000",
    image: "g1.webp",
    color: "#06d6a0",
    video: "https://www.youtube.com/watch?v=GzX1qOIO1bE"
  },
  {
    id: "unitree-h1",
    name: "H1",
    manufacturer: "Unitree Robotics",
    country: "🇨🇳 China",
    year: 2024,
    generation: "1st Gen",
    status: "Available for Purchase",
    category: "Research",
    tagline: "Full-Size Performance at Competitive Price",
    description: "Unitree H1 is a full-sized humanoid robot that offers impressive locomotion capabilities at a fraction of competitors' prices. Known for setting speed records for humanoid walking.",
    specs: {
      height: 180, weight: 47, dof: 26,
      speed: 3.3, payload: 10, battery: 4,
      ip_rating: "IP54", actuator: "Electric",
      connectivity: "Wi-Fi 6, 4G LTE"
    },
    pros: ["Fastest walking humanoid (3.3 m/s)", "Competitive pricing (~$90K)", "Excellent locomotion", "Open SDK"],
    cons: ["Limited manipulation", "No dexterous hands", "Research-focused", "Sparse documentation"],
    price: "~$90,000",
    image: "h1.webp",
    color: "#118ab2",
    video: "https://www.youtube.com/watch?v=TS_Dv5fSsRU"
  },
  {
    id: "gr-2",
    name: "GR-2",
    manufacturer: "Fourier Intelligence",
    country: "🇨🇳 China",
    year: 2025,
    generation: "2nd Gen",
    status: "Pilot Program",
    category: "Healthcare & Industrial",
    tagline: "Intelligence Meets Rehabilitation",
    description: "Fourier Intelligence's GR-2 builds on the company's expertise in rehabilitation robotics. It features advanced force control and human-robot interaction capabilities.",
    specs: {
      height: 175, weight: 63, dof: 53,
      speed: 1.4, payload: 15, battery: 2,
      ip_rating: "IP44", actuator: "Electric",
      connectivity: "Wi-Fi 6, ROS, NVIDIA Isaac"
    },
    pros: ["Highest DoF (53)", "Healthcare expertise", "Force-controlled interaction", "Multi-sector applications"],
    cons: ["Early commercial stage", "Limited ecosystem", "Newer brand recognition", "Unproven at scale"],
    price: "Contact for Quote",
    image: "gr2.webp",
    color: "#9b5de5",
    video: ""
  },
  {
    id: "walker-s2",
    name: "Walker S2",
    manufacturer: "UBTECH",
    country: "🇨🇳 China",
    year: 2025,
    generation: "S2",
    status: "Pilot Program",
    category: "Industrial & Service",
    tagline: "China's Most Advanced Humanoid",
    description: "UBTECH's Walker S2 is one of China's flagship humanoid robots, featuring advanced manipulation, vision systems, and deployment in automotive manufacturing facilities.",
    specs: {
      height: 176, weight: 70, dof: 52,
      speed: 2.0, payload: 15, battery: 2.5,
      ip_rating: "IP54", actuator: "Electric",
      connectivity: "Wi-Fi 6, 5G, BrainNet AI"
    },
    pros: ["NIO factory deployment", "Auto battery swap for 24/7 uptime", "52 DoF dexterity", "BrainNet AI stack"],
    cons: ["Limited international presence", "Closed platform", "High cost", "Early deployment stage"],
    price: "Contact for Quote",
    image: "walkers2.webp",
    color: "#e07a5f",
    video: ""
  },
  {
    id: "neo",
    name: "NEO Gamma",
    manufacturer: "1X Technologies",
    country: "🇳🇴 Norway",
    year: 2025,
    generation: "Gamma",
    status: "Pilot Program",
    category: "Home & Service",
    tagline: "Your Future Home Companion",
    description: "1X Technologies' NEO is designed specifically for home environments. With a friendly design and safe human interaction capabilities, it aims to be the first humanoid you'd welcome into your living room.",
    specs: {
      height: 168, weight: 30, dof: 39,
      speed: 1.4, payload: 25, battery: 4,
      ip_rating: "IP44", actuator: "Tendon Drive",
      connectivity: "Wi-Fi 6, NVIDIA Jetson Thor"
    },
    pros: ["Designed for home use", "25kg carry capacity", "39 DoF w/ 22-DoF hands", "Soft body safety design"],
    cons: ["Consumer-only focus", "New product category", "Requires home adaptation", "Subscription model"],
    price: "$20,000 (or $499/mo subscription)",
    image: "neo.webp",
    color: "#00b4d8",
    video: ""
  },
  {
    id: "phoenix",
    name: "Phoenix",
    manufacturer: "Sanctuary AI",
    country: "🇨🇦 Canada",
    year: 2025,
    generation: "8th Gen",
    status: "Pilot Program",
    category: "General Purpose",
    tagline: "The World's First Human-Like Intelligence in Robots",
    description: "Sanctuary AI's Phoenix combines their proprietary Carbon AI system with a humanoid form factor. It focuses on general-purpose work with human-like dexterity and cognitive abilities.",
    specs: {
      height: 170, weight: 70, dof: 71,
      speed: 1.4, payload: 25, battery: 8,
      ip_rating: "IP44", actuator: "Hydraulic/Electric",
      connectivity: "Wi-Fi 6, 5G, Carbon AI"
    },
    pros: ["Carbon AI cognitive system", "Best-in-class hands (21 DoF each)", "8-hour battery", "Magna partnership"],
    cons: ["Higher weight", "Slower movement", "Limited deployments", "Complex hybrid actuators"],
    price: "Contact for Quote",
    image: "phoenix.webp",
    color: "#f4845f",
    video: ""
  },
  {
    id: "apollo",
    name: "Apollo",
    manufacturer: "Apptronik",
    country: "🇺🇸 USA",
    year: 2025,
    generation: "Production",
    status: "Pilot Program",
    category: "Industrial",
    tagline: "Built for Work, Designed for People",
    description: "Apptronik's Apollo is designed for industrial logistics and manufacturing. Born from NASA research, it features modular design and focuses on safe human-robot collaboration.",
    specs: {
      height: 173, weight: 73, dof: 71,
      speed: 0.9, payload: 25, battery: 4,
      ip_rating: "IP54", actuator: "Electric Linear",
      connectivity: "Wi-Fi 6, NVIDIA GR00T, Fleet API"
    },
    pros: ["NASA heritage", "Mercedes-Benz partnership", "71 DoF — modular design", "22hrs daily uptime (hot-swap)"],
    cons: ["Slower walking speed", "Early commercial stage", "Limited autonomy", "High cost"],
    price: "~$50,000 (Target)",
    image: "apollo.webp",
    color: "#3a86a7",
    video: ""
  },
  {
    id: "astribot-s1",
    name: "Astribot S1",
    manufacturer: "Astribot",
    country: "🇨🇳 China",
    year: 2025,
    generation: "S1",
    status: "R&D",
    category: "Service & Home",
    tagline: "Speed & Precision Redefined",
    description: "Astribot S1 gained viral attention for its incredibly fast and precise manipulation capabilities. It can perform delicate tasks like pouring tea, writing calligraphy, and handling fragile objects at superhuman speed. Uses a wheeled omnidirectional base.",
    specs: {
      height: 170, weight: 90, dof: 23,
      speed: 0.4, payload: 10, battery: 3,
      ip_rating: "IP44", actuator: "Electric",
      connectivity: "Wi-Fi 6"
    },
    pros: ["10 m/s end-effector speed", "Sub-0.1mm precision", "Versatile task capability", "Impressive demos"],
    cons: ["Wheeled base (not bipedal)", "No commercial deployments", "Unknown pricing", "Heavy (90kg)"],
    price: "TBA",
    image: "astribot.webp",
    color: "#ff006e",
    video: ""
  },
  {
    id: "pepper",
    name: "Pepper",
    manufacturer: "SoftBank Robotics",
    country: "🇯🇵 Japan",
    year: 2014,
    generation: "Legacy",
    status: "Available",
    category: "Social & Service",
    tagline: "The Pioneer of Social Robotics",
    description: "Pepper was one of the first commercially available social humanoid robots. Though smaller and less capable than modern humanoids, it pioneered human-robot emotional interaction and remains widely deployed in retail and hospitality.",
    specs: {
      height: 120, weight: 28, dof: 20,
      speed: 0.5, payload: 0.5, battery: 12,
      ip_rating: "IP21", actuator: "Electric",
      connectivity: "Wi-Fi, 4G"
    },
    pros: ["Pioneer in social robotics", "12-hour battery life", "Proven commercial track record", "Emotion recognition"],
    cons: ["Wheeled (not bipedal)", "Very limited payload", "Aging technology", "Production discontinued in some markets"],
    price: "~$25,000 (Lease: ~$500/month)",
    image: "pepper.webp",
    color: "#ffd166",
    video: ""
  },
  {
    id: "asimo",
    name: "ASIMO",
    manufacturer: "Honda",
    country: "🇯🇵 Japan",
    year: 2000,
    generation: "Legacy",
    status: "Retired (2022)",
    category: "Research & Legacy",
    tagline: "The Grandfather of Modern Humanoids",
    description: "Honda's ASIMO (Advanced Step in Innovative Mobility) was the world's most iconic humanoid robot for over two decades. Though retired in 2022, its bipedal locomotion research laid the groundwork for every modern humanoid.",
    specs: {
      height: 130, weight: 48, dof: 57,
      speed: 2.5, payload: 0.5, battery: 1,
      ip_rating: "N/A", actuator: "Electric",
      connectivity: "Wi-Fi"
    },
    pros: ["Historic significance", "Pioneered bipedal walking", "57 DoF — still impressive", "Inspired entire industry"],
    cons: ["Retired in 2022", "No commercial availability", "Outdated AI", "Low payload"],
    price: "Retired (Was ~$2.5M R&D cost)",
    image: "asimo.webp",
    color: "#adb5bd",
    video: ""
  },
  {
    id: "cl-1",
    name: "CL-1",
    manufacturer: "LimX Dynamics",
    country: "🇨🇳 China",
    year: 2025,
    generation: "1st Gen",
    status: "R&D",
    category: "Research",
    tagline: "Reinforcement Learning Locomotion Master",
    description: "LimX Dynamics' CL-1 showcases state-of-the-art reinforcement learning-based locomotion, demonstrating impressive ability to traverse unstructured terrain including stairs, slopes, and rough ground.",
    specs: {
      height: 180, weight: 70, dof: 30,
      speed: 1.8, payload: 10, battery: 3,
      ip_rating: "IP44", actuator: "Electric",
      connectivity: "Wi-Fi 6"
    },
    pros: ["Best-in-class RL locomotion", "Handles rough terrain", "Lightweight design", "Strong research pedigree"],
    cons: ["Research stage only", "Limited manipulation", "No commercial availability", "Small company"],
    price: "TBA",
    image: "cl1.webp",
    color: "#7209b7",
    video: ""
  },
  {
    id: "ameca",
    name: "Ameca",
    manufacturer: "Engineered Arts",
    country: "🇬🇧 UK",
    year: 2021,
    generation: "Mark 2",
    status: "Available",
    category: "Social & Entertainment",
    tagline: "The World's Most Expressive Robot",
    description: "Ameca by Engineered Arts is the most advanced social humanoid robot, known for its incredibly lifelike facial expressions. It serves as a platform for AI and HRI research, and has gone viral multiple times for its eerily human-like reactions.",
    specs: { height: 187, weight: 62, dof: 61, speed: 0, payload: 2, battery: 6, ip_rating: "N/A", actuator: "Electric", connectivity: "Wi-Fi 6, GPT-4 Integration" },
    pros: ["Most realistic facial expressions", "61 DoF — 27 in face alone", "GPT-4 & multi-LLM integration", "Modular Tritium OS platform"],
    cons: ["Cannot walk (static platform)", "Very expensive", "Entertainment-focused only", "No locomotion capability"],
    price: "~$150,000+",
    image: "ameca.webp", color: "#e63946", video: ""
  },
  {
    id: "4ne-1",
    name: "4NE-1",
    manufacturer: "Neura Robotics",
    country: "🇩🇪 Germany",
    year: 2025,
    generation: "1st Gen",
    status: "Pilot Program",
    category: "Manufacturing",
    tagline: "Cognitive Intelligence for Industry",
    description: "Neura Robotics' 4NE-1 is a cognitive humanoid designed for manufacturing environments. Backed by significant European investment, it combines advanced perception with industrial-grade reliability for factory automation.",
    specs: { height: 180, weight: 80, dof: 55, speed: 1.4, payload: 20, battery: 4, ip_rating: "IP54", actuator: "Electric", connectivity: "Wi-Fi 6, 5G, Edge AI" },
    pros: ["Strong European engineering", "55 DoF — full-body tactile skin", "Cognitive AI perception", "€300M+ funding"],
    cons: ["Early deployment stage", "Heavy for its class", "Limited global presence", "High cost"],
    price: "Contact for Quote",
    image: "4ne1.webp", color: "#457b9d", video: ""
  },
  {
    id: "kepler-k2",
    name: "Forerunner K2",
    manufacturer: "Kepler Robot",
    country: "🇨🇳 China",
    year: 2025,
    generation: "2nd Gen",
    status: "Pilot Program",
    category: "Industrial",
    tagline: "Industrial Humanoid Built for Scale",
    description: "Kepler's Forerunner K2 is designed for industrial environments with focus on cost-effective mass production. It features robust build quality and competitive pricing targeting large-scale factory deployment.",
    specs: { height: 178, weight: 80, dof: 52, speed: 1.1, payload: 30, battery: 8, ip_rating: "IP54", actuator: "Electric", connectivity: "Wi-Fi 6, 5G, KeplerBrain" },
    pros: ["Competitive pricing", "Designed for mass production", "52 DoF — 11-DoF tactile hands", "8-hour battery"],
    cons: ["Heavy build", "Limited international sales", "Newer brand", "Few real deployments"],
    price: "~$30,000 (Target)",
    image: "k2.webp", color: "#264653", video: ""
  },
  {
    id: "iron",
    name: "Iron",
    manufacturer: "XPeng Robotics",
    country: "🇨🇳 China",
    year: 2025,
    generation: "1st Gen",
    status: "R&D",
    category: "General Purpose",
    tagline: "From EVs to Humanoids",
    description: "XPeng Robotics' Iron humanoid leverages XPeng's autonomous driving AI expertise to create a general-purpose robot. Backed by the automotive giant's massive R&D infrastructure and supply chain.",
    specs: { height: 173, weight: 70, dof: 82, speed: 1.1, payload: 15, battery: 5, ip_rating: "IP44", actuator: "Electric", connectivity: "Wi-Fi 6, 5G, Turing AI" },
    pros: ["82 DoF — most articulated humanoid", "XPeng automotive AI (3000 TOPS)", "All-solid-state battery", "720° Eagle-Eye vision"],
    cons: ["Early R&D stage", "No commercial deployments", "Unproven track record", "Chinese market focus"],
    price: "TBA",
    image: "iron.webp", color: "#2d6a4f", video: ""
  },
  {
    id: "agibot-a2",
    name: "AgiBot A2",
    manufacturer: "AgiBot (Zhiyuan)",
    country: "🇨🇳 China",
    year: 2025,
    generation: "A2",
    status: "Mass Production",
    category: "Industrial",
    tagline: "China's Mass-Production Leader",
    description: "AgiBot (formerly Zhiyuan) is one of the highest-volume humanoid robot manufacturers globally. The A2 model targets industrial automation with aggressive pricing and proven factory deployments across Chinese manufacturing facilities.",
    specs: { height: 170, weight: 65, dof: 49, speed: 3.3, payload: 15, battery: 2, ip_rating: "IP54", actuator: "Electric", connectivity: "Wi-Fi 6, 5G, Fleet" },
    pros: ["Highest production volume in China", "Competitive pricing", "Factory-proven deployments", "49 DoF — 19-DoF dexterous hands"],
    cons: ["Limited outside China", "Documentation in Chinese", "Rapidly iterating (stability concerns)", "Brand recognition outside Asia"],
    price: "~$25,000-40,000",
    image: "agibot.webp", color: "#e76f51", video: ""
  },
  {
    id: "sophia",
    name: "Sophia",
    manufacturer: "Hanson Robotics",
    country: "🇭🇰 Hong Kong",
    year: 2016,
    generation: "Legacy / Ongoing",
    status: "Available",
    category: "Social & Entertainment",
    tagline: "The World's Most Famous Robot",
    description: "Sophia is the world's most recognizable humanoid robot and the first to receive citizenship (Saudi Arabia, 2017). While not bipedal, she represents a milestone in social robotics and AI-human interaction, appearing on countless media outlets worldwide.",
    specs: { height: 167, weight: 20, dof: 83, speed: 0, payload: 0, battery: 8, ip_rating: "N/A", actuator: "Electric", connectivity: "Wi-Fi, Cloud AI" },
    pros: ["Most famous robot globally", "First robot citizen", "83 DoF total (62 in face)", "Excellent for HRI research"],
    cons: ["Cannot walk independently", "More PR than utility", "Limited practical applications", "Older technology base"],
    price: "Contact for Quote",
    image: "sophia.webp", color: "#e9c46a", video: ""
  },
  {
    id: "cyberone",
    name: "CyberOne",
    manufacturer: "Xiaomi",
    country: "🇨🇳 China",
    year: 2022,
    generation: "1st Gen",
    status: "R&D",
    category: "General Purpose",
    tagline: "Xiaomi's Entry into Humanoid Robotics",
    description: "CyberOne is Xiaomi's first humanoid robot, unveiled by CEO Lei Jun in 2022. It features emotion recognition, 3D space perception, and was designed as a research platform for Xiaomi's broader robotics ambitions.",
    specs: { height: 177, weight: 52, dof: 21, speed: 1.0, payload: 1.5, battery: 2, ip_rating: "N/A", actuator: "Electric", connectivity: "Wi-Fi 6, Mi-AI" },
    pros: ["Xiaomi's massive R&D resources", "Emotion recognition capability", "Affordable development potential", "Strong IoT ecosystem integration"],
    cons: ["Very early prototype", "Low payload capacity", "Slow movement", "No commercial timeline"],
    price: "~$100,000 (R&D only)",
    image: "cyberone.webp", color: "#4361ee", video: ""
  },
  {
    id: "talos",
    name: "TALOS",
    manufacturer: "PAL Robotics",
    country: "🇪🇸 Spain",
    year: 2017,
    generation: "Ongoing",
    status: "Available",
    category: "Research",
    tagline: "Europe's Premier Research Humanoid",
    description: "TALOS by PAL Robotics is one of the leading full-size humanoid platforms for academic research. Used by top European universities and research labs, it's known for its robust ROS2 integration and open software stack.",
    specs: { height: 175, weight: 95, dof: 32, speed: 1.0, payload: 6, battery: 3, ip_rating: "IP44", actuator: "Electric/Hydraulic", connectivity: "Wi-Fi, ROS2" },
    pros: ["Best-in-class research platform", "Full ROS2 integration", "Proven track record (7+ years)", "Open software stack"],
    cons: ["Heavy (95kg)", "Slow walking speed", "Expensive for academia", "Not designed for commercial use"],
    price: "~$400,000+",
    image: "talos.webp", color: "#fb8500", video: ""
  },
  {
    id: "kuavo",
    name: "KUAVO",
    manufacturer: "Leju Robotics",
    country: "🇨🇳 China",
    year: 2024,
    generation: "1st Gen",
    status: "Available for Purchase",
    category: "Research & Education",
    tagline: "Dynamic Bipedal Research Platform",
    description: "Leju Robotics' KUAVO is a highly dynamic bipedal humanoid known for its impressive locomotion capabilities. It has demonstrated backflips and dynamic movements, positioning it as a compelling research and education platform.",
    specs: { height: 145, weight: 45, dof: 30, speed: 1.3, payload: 5, battery: 3, ip_rating: "IP44", actuator: "Electric", connectivity: "Wi-Fi 6, KaihongOS SDK" },
    pros: ["Dynamic locomotion (backflips)", "Competitive research pricing", "Open SDK for developers", "Impressive agility for size"],
    cons: ["Smaller form factor", "Low payload", "Limited manipulation", "Newer company"],
    price: "~$50,000",
    image: "kuavo.webp", color: "#7b2cbf", video: ""
  },
  {
    id: "bumi",
    name: "Bumi",
    manufacturer: "Noetix Robotics",
    country: "🇨🇳 China",
    year: 2025,
    generation: "1st Gen",
    status: "Available for Purchase",
    category: "Research & Education",
    tagline: "Ultra-Affordable Consumer Humanoid",
    description: "Noetix Robotics' Bumi is a compact, affordable consumer humanoid robot from Beijing. At just ~$1,400, it sold out rapidly on JD.com and brings humanoid robotics to the mass consumer and education market.",
    specs: { height: 94, weight: 12, dof: 21, speed: 0.5, payload: 1, battery: 1.5, ip_rating: "IP44", actuator: "Electric", connectivity: "Wi-Fi, JoyInside 2.0 AI" },
    pros: ["Ultra-affordable (~$1,400)", "Lightweight & portable", "Block-based programming", "Sold out rapidly on JD.com"],
    cons: ["Very small form factor", "Minimal payload", "Short battery life", "Limited autonomy"],
    price: "~$1,400 (¥9,998)",
    image: "bumi.webp", color: "#2ec4b6", video: ""
  },
  {
    id: "thr3",
    name: "T-HR3",
    manufacturer: "Toyota",
    country: "🇯🇵 Japan",
    year: 2017,
    generation: "3rd Gen",
    status: "R&D",
    category: "Research",
    tagline: "Toyota's Telepresence Humanoid",
    description: "Toyota's T-HR3 is a partner robot designed for teleoperation, featuring a Master Maneuvering System that allows operators to control the robot remotely with natural body movements. It represents Toyota's vision of robots as human partners.",
    specs: { height: 154, weight: 75, dof: 32, speed: 0.5, payload: 5, battery: 2, ip_rating: "N/A", actuator: "Electric", connectivity: "Wi-Fi, 5G Teleoperation" },
    pros: ["Advanced teleoperation system", "Toyota engineering quality", "Force-feedback control", "Disaster response potential"],
    cons: ["Requires human operator", "R&D only — not commercial", "Slow autonomous movement", "Heavy for its height"],
    price: "R&D Only",
    image: "thr3.webp", color: "#adb5bd", video: ""
  },
  {
    id: "unitree-r1",
    name: "R1 Air",
    manufacturer: "Unitree Robotics",
    country: "🇨🇳 China",
    year: 2025,
    generation: "1st Gen",
    status: "Pre-order",
    category: "Home & Service",
    tagline: "The Ultra-Affordable Home Humanoid",
    description: "Unitree R1 Air is a compact companion humanoid robot announced for the home market. Leveraging Unitree's manufacturing prowess, it targets an incredibly low price point to bring humanoid robotics to everyday consumers.",
    specs: { height: 123, weight: 27, dof: 20, speed: 2.5, payload: 3, battery: 1, ip_rating: "IP44", actuator: "Electric", connectivity: "Wi-Fi 6, Bluetooth 5.2, LMM AI" },
    pros: ["Most affordable humanoid ($4,900)", "Unitree manufacturing scale", "Cartwheels & acrobatics", "Open joint & sensor interfaces"],
    cons: ["Small form factor", "Very low payload", "Only ~1hr battery", "Limited manipulation"],
    price: "~$4,900",
    image: "r1air.webp", color: "#06d6a0", video: ""
  },
  {
    id: "menteebot",
    name: "MenteeBot V3",
    manufacturer: "Mentee Robotics",
    country: "🇮🇱 Israel",
    year: 2025,
    generation: "V3",
    status: "Pilot Program",
    category: "General Purpose",
    tagline: "AI-First Humanoid from Israel",
    description: "Mentee Robotics, co-founded by AI pioneer Amnon Shashua (Mobileye), brings autonomous driving AI expertise to humanoid robotics. MenteeBot V3 uses end-to-end Sim2Real AI learning with proprietary high-torque actuators.",
    specs: { height: 175, weight: 70, dof: 40, speed: 1.5, payload: 25, battery: 5, ip_rating: "IP44", actuator: "Electric", connectivity: "Wi-Fi 6, NVIDIA Jetson Orin" },
    pros: ["Mobileye founder's new venture", "Sim2Real reinforcement learning", "25kg payload capacity", "360° fisheye vision"],
    cons: ["Early pilot stage", "No public pricing", "Small team", "Limited deployments"],
    price: "TBA",
    image: "menteebot.webp", color: "#0077b6", video: ""
  },
  {
    id: "galbot-g1",
    name: "Galbot G1",
    manufacturer: "Galbot",
    country: "🇨🇳 China",
    year: 2025,
    generation: "1st Gen",
    status: "Pilot Program",
    category: "Manufacturing",
    tagline: "Embodied Intelligence for Factories",
    description: "Galbot's G1 is a dual-arm humanoid robot with omnidirectional wheeled chassis, designed for flexible manufacturing and retail tasks. It features 7-DoF arms with up to 2.4m workspace reach and 10-hour battery life.",
    specs: { height: 173, weight: 80, dof: 24, speed: 1.0, payload: 10, battery: 10, ip_rating: "IP54", actuator: "Electric", connectivity: "Wi-Fi 6, Fleet Management" },
    pros: ["10-hour battery life", "2.4m workspace reach", "Omnidirectional mobility", "Factory-proven pilots"],
    cons: ["Wheeled base (not bipedal)", "Limited dexterity (24 DoF)", "Small brand recognition", "Early commercial stage"],
    price: "Contact for Quote",
    image: "galbot.webp", color: "#6c757d", video: ""
  },
  {
    id: "robotera-star1",
    name: "STAR1",
    manufacturer: "RobotEra",
    country: "🇨🇳 China",
    year: 2025,
    generation: "1st Gen",
    status: "Pilot Program",
    category: "General Purpose",
    tagline: "Speed Meets Full-Body Intelligence",
    description: "RobotEra's STAR1 is a full-size bipedal humanoid capable of running at 3.6 m/s. It features 55 DoF with 12-DoF XHAND dexterous hands, designed for both industrial and service applications.",
    specs: { height: 171, weight: 63, dof: 55, speed: 3.6, payload: 20, battery: 3, ip_rating: "IP44", actuator: "Electric", connectivity: "Wi-Fi 6, 5G, Cloud AI" },
    pros: ["3.6 m/s running speed", "55 DoF — 12-DoF XHAND hands", "Versatile deployment", "Strong RL locomotion"],
    cons: ["Newer company", "Limited deployments", "Short battery life (3hr)", "Unproven at scale"],
    price: "Contact for Quote",
    image: "star1.webp", color: "#e07a5f", video: ""
  }
];

// News data — Real verified headlines May 2026
const NEWS = [
  { id: 1, title: "Japan Airlines Deploys Humanoid Robots at Haneda Airport", date: "2026-05-18", category: "Deployment", robot: null, excerpt: "JAL began a 3-year operational trial with Unitree-based humanoids for baggage loading, container transport, and cabin cleaning at Tokyo's Haneda Airport." },
  { id: 2, title: "BMW Expands Figure AI Pilot to Leipzig Factory", date: "2026-05-14", category: "Deployment", robot: "figure-03", excerpt: "Following success at Spartanburg (30K vehicles produced), BMW is scaling Figure AI humanoid deployment to its Leipzig plant for EV battery assembly." },
  { id: 3, title: "Schaeffler Signs 1,000+ Robot Deal with Humanoid Startup", date: "2026-05-10", category: "Business", robot: null, excerpt: "London-based startup 'Humanoid' signed a multi-year agreement with German industrial giant Schaeffler targeting 1,000+ humanoid robots across global facilities by 2032." },
  { id: 4, title: "Tesla Optimus Production-Intent Units Begin Summer 2026", date: "2026-05-08", category: "Production", robot: "optimus", excerpt: "Tesla confirmed production of Optimus production-intent units will begin at Fremont factory this summer, with high-volume production targeted for 2027." },
  { id: 5, title: "Global Robotics Market Reaches $38 Billion — 34% YoY Growth", date: "2026-05-05", category: "Market", robot: null, excerpt: "Counterpoint Research reports the global robotics market reached $38B in 2026. Humanoid sector alone valued at $6.24B with 12 commercial platforms now available." },
  { id: 6, title: "12 Commercial Humanoid Platforms Now Available for Purchase", date: "2026-05-01", category: "Market", robot: null, excerpt: "The number of commercially available humanoid robot platforms has quadrupled from just 3 in 2024 to 12 in 2026, signaling rapid industry maturation." },
  { id: 7, title: "VLA Models Used in 40% of New Humanoid Deployments", date: "2026-04-28", category: "Technology", robot: null, excerpt: "Vision-Language-Action models are now integrated in 40% of new humanoid robot deployments, enabling robots to better understand and interact with environments." },
  { id: 8, title: "1X Technologies NEO Begins First Consumer Shipments", date: "2026-04-22", category: "Deployment", robot: "neo", excerpt: "1X Technologies' NEO humanoid, designed for home environments, has started its first customer shipments in 2026, entering the mass consumer market." }
];

// Stat specs metadata
const SPEC_LABELS = {
  height: { label: "Height", unit: "cm", icon: "📏" },
  weight: { label: "Weight", unit: "kg", icon: "⚖️" },
  dof: { label: "Degrees of Freedom", unit: "", icon: "🦾" },
  speed: { label: "Max Speed", unit: "m/s", icon: "⚡" },
  payload: { label: "Payload", unit: "kg", icon: "📦" },
  battery: { label: "Battery Life", unit: "hrs", icon: "🔋" },
  ip_rating: { label: "IP Rating", unit: "", icon: "🛡️" },
  actuator: { label: "Actuator Type", unit: "", icon: "⚙️" },
  connectivity: { label: "Connectivity", unit: "", icon: "📡" }
};

const CATEGORIES = ["All", "Industrial", "General Purpose", "AI-Native", "Logistics", "Research & Education", "Research", "Healthcare & Industrial", "Industrial & Service", "Home & Service", "Service & Home", "Social & Service", "Research & Legacy", "Social & Entertainment", "Manufacturing", "Service & Hospitality"];

const MANUFACTURERS = [...new Set(ROBOTS.map(r => r.manufacturer))];
